###
http://localhost:3000/v1/test


###

http://localhost:3000/v1/testauth
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU0YmIyMTY1LTcxZTEtNDFhNi1hZjNlLTdkYTRhMGUxZTJjMSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTUxMDI0MDAsImlhdCI6MTY2MzU2NjQwMCwiaXNzIjoic2VydmljZSBwcm9qZWN0Iiwic3ViIjoiMTIzNDU2Nzg5IiwiUm9sZXMiOlsiQURNSU4iXX0.udBormPz75-NdZ8cNnKTjsOT5lG6dIVsHGOPqxFhBTqkwxF_Wm3xQpECqIRH4dKFdQ6LgQ6QNBIMwdqte5PAxg5shld1zWfxeM01nP2yVPW1E0dPbM3vnMzRm1YoynQvlGHzA1ExyFiCHtAdWlq32cCYq0ezouzpcVdfOJ5P3RvWq0lXcmwMkPxSDq6GS52pyQKfn7VJHoZkmZ0MtIPQe_SaI5uoX7nfwT-pBjfu5QHq2lznIh5tmUmK5XoyRtPWZ4eJ1PImsjVnFPOywUCrDVHw5XT95QpVvXJmtkLaminsyPKu6XnSfTwNv2k0DFOy5-dfQKnpNfnBuXSEP4djpg

###
http://localhost:3000/v1/testauth
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjU0YmIyMTY1LTcxZTEtNDFhNi1hZjNlLTdkYTRhMGUxZTJjMSIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTUxNDA2MTgsImlhdCI6MTY2MzYwNDYxOCwiaXNzIjoic2VydmljZSBwcm9qZWN0Iiwic3ViIjoiMTIzNDU2Nzg5IiwiUm9sZXMiOlsiVVNFUiJdfQ.A6cXoSlb9_lNVRKGY6VaxObr1jLi2JFG0umzB5ay9DMtox6Qsgj0RUYNB3h2iLAHbI13AzX4_vkP_jYqndxX_N1VCCbjzPPRInFCFZzRu8gVin-Je2fhPh5zG99QL4VlFoE3i6aWecdOkkDTY9CSmL_blw8T_BsFYfge67683c_81yutJ--iZuoZSDEYisJWdXMuQO4BdwO1i3CADbFSe_HBGlQvQCBh_NdBwBKux-uiLntH8nPYzWG4rCQ0M97DZB36qYTYEHlq_MhFQfW-DChDDuGtaUoBA33NRfOPJQyolX4McL0yl-f9MRWZ7i8QN1va9m0t7RrxLf5VIzrSsQ